### ISSUE TITLE
Invalid variable declaration in `examples/src/log.h`

### ISSUE THREAD

**Issue by ViralTaco** [GordonZhang2024/log.cc#1]
Answering your (closed) [stackoverflow question](https://stackoverflow.com/questions/78580772/it-seems-like-there-is-a-name-conflict-in-my-code-but-i-cant-find-where-is-it).
Class forward declaration here:
https://github.com/GordonZhang2024/log.cc/blob/8b7c69ce4dcf75526cb4ae1573d6bf8a65d44857/examples/src/log.h#L25
Function declaration (and not a variable with default value) here:
https://github.com/GordonZhang2024/log.cc/blob/8b7c69ce4dcf75526cb4ae1573d6bf8a65d44857/examples/src/log.h#L51
When you declare a function inside a class definition the return type of said function needs to be ODR accessible. (cf: [this so answer](https://stackoverflow.com/a/45901227/9282847)).

**Comment by GordonZhang2024** [comment]
I've fixed this problem. Thanks
